### ISSUE TITLE
MD5 should no longer be a default, SHA1 is questionable, BLAKE2s is a good add-on

### ISSUE THREAD

**Issue by grempe** [ioquatix/fingerprint#4]
MD5 is really no longer safe to use for anything that needs to be strongly verified for integrity. SHA1 is also right on the cusp of no longer being safe to use and is being phased out in a wide variety of cryptographic hash use cases (e.g. SHA1 is no longer allowed in TLS certificates, and browsers will refuse to serve pages using SHA1 TLS certs next year).

I think these are ok to still support for legacy use, but I would suggest changing the default to be only SHA256 and then allow people to add any additional hashes that they think they need as CLI options.

Bonus Points

I would also suggest adding BLAKE2s which is a modern and secure hash, and also very fast and is being used quite widely now. Here is a high quality ruby gem that implements it (disclosure, I helped the author extensively test and contributed to it) and I think it would be quite easy to add:

https://github.com/franckverrot/blake2

There is a `b2sum` command that can be installed on macOS with homebrew to test it out as a CLI:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/b2sum.rb

```
brew install b2sum
man b2sum
```

Cheers!

Glenn

**Comment by grempe** [comment]
Please note, I also I added a pull request for SHA2.384

https://github.com/ioquatix/fingerprint/pull/3

**Comment by ioquatix** [comment]
This is awesome, thanks so much for your contributions and ideas. I'm wondering if you will forgive me for taking so long to get back to you.

You are totally correct. MD5 is not for security. Would you consider it okay for verifying file copies in non-malicious situations? Like, does MD5 have a good response to single bit errors, and multi-bit errors, even in large files?

I would be happy to add support for more checksums.

I believe it would be best if it worked the same way that Digest module works in Ruby for maximum ease of integration. What do you think?

**Comment by ioquatix** [comment]
If you submit a PR to add support for BLAKE2, I will merge it.

**Comment by ioquatix** [comment]
I added a spec for all existing checksums except SHA1..

Do you think we should remove SHA1? We could at least mark it as deprecated for new fingerprints.

**Comment by ioquatix** [comment]
Here is the spec FYI.

https://github.com/ioquatix/fingerprint/blob/master/spec/fingerprint/scanner_spec.rb

Also, I released a patch release with SHA2.384

**Comment by grempe** [comment]
Hi,

Thanks for being receptive to the changes. 

I don't think you need to remove sha1. I would just not encourage its use.

For md5 perhaps you should consider removing it, or making it for verification of existing files only (no new creation).

https://www.quora.com/Cryptography-Why-are-MD5-and-SHA1-called-broken-algorithms

http://www.mscs.dal.ca/~selinger/md5collision/

I think using sha256 as the single default hash you end up with a good system that can be cryptographically signed without fearing that collisions could be found for the signed files.

I'll take a look at doing a Blake PR. 

Cheers

**Comment by grempe** [comment]
Added pull request to address all of the above (with the exception that there is no change to MD5 for creation, it is still allowed, but you might want to change that).

https://github.com/ioquatix/fingerprint/pull/5
