### ISSUE TITLE
Not clear how to avoid writing index.fingerprint to source area

### ISSUE THREAD

**Issue by aghadjip** [ioquatix/fingerprint#7]
EX
Scanning a RO mounted system would exit with RO filesystem error

index.fingerprint still gets written to scanned dir even if > redirect is used.

**Comment by ioquatix** [comment]
`fingerprint analyze` and `fingerprint verify` write to the current directory and are for archival purposes.

To write the result somewhere else, you can specify `-n path/to/index.fingerprint` to both commands for the same behaviour.
